Create register page
miguelhenaoa/open-word pull request #2
Opened 2023-01-24 14:05 UTC by juanpabotero

Queda pendiente revisar cuando se hace el submit del formulario, se marcan los campos como faltantes .

2023-01-25 00:22 UTC, miguelhenao reviewed
Excelente trabajo, unos pequeños comments

2023-01-25 00:22 UTC, miguelhenao commented on apps/landing-page/src/app/pages/register/register.component.ts
> +    this.dialog.open(DialogComponent);
Esto lo podemos hacer con sweetalert2,

2023-01-25 00:22 UTC, miguelhenao commented on apps/landing-page/src/app/pages/register/register.component.ts
> +  submitForm() {
Luego de que envíe el formulario, mostrar la alerta y devolver a la página de inicio

2023-01-25 00:24 UTC, miguelhenao commented on apps/landing-page/src/app/pages/register/register.component.html
> +        Foto de la cédula
Excelente componente, me quedaría faltando que me muestre el nombre del archivo, así estoy seguro de que si cargó correctamente

2023-01-25 00:24 UTC, miguelhenao requested changes
Uno más jeje

2023-01-29 03:51 UTC, miguelhenaoa approved these changes

2023-01-29 03:51 UTC, miguelhenaoa commented
LGTM! 🚀

2023-01-29 03:51 UTC, merged